name: xir_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies: 
  flutter: 
    sdk: flutter 
  web_socket_channel: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.0.6 
  http: ^0.13.3 
  sqflite: ^2.0.2+1 
  path: 
  just_audio: ^0.9.29
  record: ^5.2.0
  speech_to_text: ^7.0.0  # Обновлено до версии 7.0.0
  flutter_sound: ^9.3.0
  cupertino_icons: ^1.0.8
  flutter_highlight: ^0.7.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.1.0+2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
